# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.* OR cat:nlin.CD OR cat:q-bio.* OR cat:eess.* OR cat:stat.*'

# 検索キーワード
keywords:
        heart rate: 2
        depression: 2
        poincare: 1
        lorenz: 1
        autonomic nervous: 2
        electrodermal: 2
        nanopore: 3
        optical: 3
        nano: 3
        photonics: 3
        plasmon: 3
        near field: 2
        
# 通知の閾値
score_threshold: 2
