# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:cs.* OR cat:nlin.CD OR cat:q-bio.* OR cat:eess.* OR cat:stat.*'

# 検索キーワード
keywords:
        heart rate: 2
        depression: 2
        poincare: 2
        lorenz: 2
        autonomic nervous: 2
        electrodermal: 2
        nanopore: 3
        nano photonics: 2
        plasmon: 2
        near field: 2
        
# 通知の閾値
score_threshold: 2
